//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2019
{
    using System;
    using System.Collections.Generic;
    
    public partial class Absence
    {
        public int IdAbsence { get; set; }
        public Nullable<int> IdAbsenceType { get; set; }
        public Nullable<int> IdEmployee { get; set; }
        public Nullable<System.DateTime> StartOfAbsence { get; set; }
        public Nullable<System.DateTime> EndOfAbsence { get; set; }
    
        public virtual AbsenceType AbsenceType { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
