//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2019
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntranceControlView
    {
        public int IdSfDetail { get; set; }
        public string SfCode { get; set; }
        public Nullable<double> Thickness { get; set; }
        public Nullable<double> Width { get; set; }
        public Nullable<double> SfWeight { get; set; }
        public string Color { get; set; }
        public string ChemicalComposition { get; set; }
    }
}
