//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2019
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntranceControl
    {
        public int IdEntranceControl { get; set; }
        public int IdSfDetail { get; set; }
        public int IdEmployee { get; set; }
        public System.DateTime ControlDate { get; set; }
        public bool ControlStatus { get; set; }
        public string Comments { get; set; }
        public int Quantity { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual SfOrderDetail SfOrderDetail { get; set; }
        public virtual SfOrderDetail SfOrderDetail1 { get; set; }
    }
}
