//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2019
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expense
    {
        public int IdExpense { get; set; }
        public Nullable<int> IdDepartment { get; set; }
        public Nullable<int> IdInvoice { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Invoice Invoice { get; set; }
    }
}
