//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2019
{
    using System;
    using System.Collections.Generic;
    
    public partial class FailureMaintenance
    {
        public int IdFailureMaint { get; set; }
        public int IdFailure { get; set; }
        public int IdMaintenance { get; set; }
    
        public virtual Failure Failure { get; set; }
        public virtual Maintenance Maintenance { get; set; }
    }
}
