//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2019
{
    using System;
    using System.Collections.Generic;
    
    public partial class Failure
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Failure()
        {
            this.FailureMaintenances = new HashSet<FailureMaintenance>();
        }
    
        public int IdFailure { get; set; }
        public int IdProces { get; set; }
        public string Specification { get; set; }
        public System.DateTime FailureDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FailureMaintenance> FailureMaintenances { get; set; }
        public virtual ProductionProce ProductionProce { get; set; }
    }
}
