//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2019
{
    using System;
    using System.Collections.Generic;
    
    public partial class Machine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Machine()
        {
            this.Maintenances = new HashSet<Maintenance>();
        }
    
        public int IdMachine { get; set; }
        public int IdMachineType { get; set; }
        public string MachineName { get; set; }
        public string ProducerMachine { get; set; }
        public Nullable<int> ProductionYear { get; set; }
        public Nullable<float> PowerMachine { get; set; }
        public string WorkingArea { get; set; }
        public string CatalogMachineNr { get; set; }
        public float MetersPerHour { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Maintenance> Maintenances { get; set; }
        public virtual MachineType MachineType { get; set; }
    }
}
