//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2019
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maintenance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Maintenance()
        {
            this.EmployeePlans = new HashSet<EmployeePlan>();
            this.FailureMaintenances = new HashSet<FailureMaintenance>();
            this.Realizations = new HashSet<Realization>();
        }
    
        public int IdMaintenance { get; set; }
        public int IdMachine { get; set; }
        public int IdMaintType { get; set; }
        public int IdMaintDesc { get; set; }
        public System.DateTime DateAcceptOrder { get; set; }
        public System.DateTime StartDatePlan { get; set; }
        public System.DateTime EndDatePlan { get; set; }
        public string MaintenanceNr { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeePlan> EmployeePlans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FailureMaintenance> FailureMaintenances { get; set; }
        public virtual Machine Machine { get; set; }
        public virtual MaintDescription MaintDescription { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Realization> Realizations { get; set; }
        public virtual MaintType MaintType { get; set; }
    }
}
