//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2019
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutControl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OutControl()
        {
            this.OutputProductMeasurements = new HashSet<OutputProductMeasurement>();
        }
    
        public int IdProcess { get; set; }
        public int IdEmployee { get; set; }
        public System.DateTime StartControlDate { get; set; }
        public Nullable<System.DateTime> EndControlDate { get; set; }
        public double WidthAcceptableDeviation { get; set; }
        public double LenghtAcceptableDeviation { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual ProductionProcess ProductionProcess { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OutputProductMeasurement> OutputProductMeasurements { get; set; }
    }
}
