//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2019
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PartOrder()
        {
            this.PartOrderDetails = new HashSet<PartOrderDetail>();
        }
    
        public int IdPartOrder { get; set; }
        public int IdSupplier { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string StatusPartOrder { get; set; }
        public int CostPartOrder { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartOrderDetail> PartOrderDetails { get; set; }
    }
}
