//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2019
{
    using System;
    using System.Collections.Generic;
    
    public partial class Part
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Part()
        {
            this.MaintParts = new HashSet<MaintPart>();
            this.PartRequests = new HashSet<PartRequest>();
            this.PartOrderDetails = new HashSet<PartOrderDetail>();
        }
    
        public int IdPart { get; set; }
        public int IdPartType { get; set; }
        public int IdUnit { get; set; }
        public string PartName { get; set; }
        public string Producer { get; set; }
        public int CatalogPartNr { get; set; }
        public int QuantityWarehouse { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaintPart> MaintParts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartRequest> PartRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartOrderDetail> PartOrderDetails { get; set; }
        public virtual PartType PartType { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
