//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2019
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PartRequest()
        {
            this.PartOrderRequests = new HashSet<PartOrderRequest>();
        }
    
        public int IdPartRequest { get; set; }
        public int IdPart { get; set; }
        public int Quantity { get; set; }
        public int StatusPart { get; set; }
        public System.DateTime RequestDate { get; set; }
    
        public virtual Part Part { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartOrderRequest> PartOrderRequests { get; set; }
    }
}
