//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2019
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RoofingCompanyEntities : DbContext
    {
        public RoofingCompanyEntities()
            : base("name=RoofingCompanyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Absence> Absences { get; set; }
        public virtual DbSet<AbsenceType> AbsenceTypes { get; set; }
        public virtual DbSet<Accident> Accidents { get; set; }
        public virtual DbSet<Allocation> Allocations { get; set; }
        public virtual DbSet<Contract> Contracts { get; set; }
        public virtual DbSet<Contractor> Contractors { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Education> Educations { get; set; }
        public virtual DbSet<EducationLevel> EducationLevels { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<EmployeePlan> EmployeePlans { get; set; }
        public virtual DbSet<EntranceControl> EntranceControls { get; set; }
        public virtual DbSet<Expense> Expenses { get; set; }
        public virtual DbSet<Failure> Failures { get; set; }
        public virtual DbSet<FailureMaintenance> FailureMaintenances { get; set; }
        public virtual DbSet<FEMAnalysi> FEMAnalysis { get; set; }
        public virtual DbSet<Invoice> Invoices { get; set; }
        public virtual DbSet<InvoiceType> InvoiceTypes { get; set; }
        public virtual DbSet<Machine> Machines { get; set; }
        public virtual DbSet<MachineType> MachineTypes { get; set; }
        public virtual DbSet<MaintDescription> MaintDescriptions { get; set; }
        public virtual DbSet<Maintenance> Maintenances { get; set; }
        public virtual DbSet<MaintPart> MaintParts { get; set; }
        public virtual DbSet<MaintType> MaintTypes { get; set; }
        public virtual DbSet<MedicalExamination> MedicalExaminations { get; set; }
        public virtual DbSet<OrderCustomer> OrderCustomers { get; set; }
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
        public virtual DbSet<OutControl> OutControls { get; set; }
        public virtual DbSet<Outsourcing> Outsourcings { get; set; }
        public virtual DbSet<OutsourcingCommitment> OutsourcingCommitments { get; set; }
        public virtual DbSet<OutsourcingType> OutsourcingTypes { get; set; }
        public virtual DbSet<Part> Parts { get; set; }
        public virtual DbSet<PartOrder> PartOrders { get; set; }
        public virtual DbSet<PartOrderDetail> PartOrderDetails { get; set; }
        public virtual DbSet<PartOrderRequest> PartOrderRequests { get; set; }
        public virtual DbSet<PartRequest> PartRequests { get; set; }
        public virtual DbSet<PartType> PartTypes { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<PlannedProduction> PlannedProductions { get; set; }
        public virtual DbSet<PlannedProductionEmployeeDetail> PlannedProductionEmployeeDetails { get; set; }
        public virtual DbSet<Position> Positions { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductionProce> ProductionProces { get; set; }
        public virtual DbSet<Realization> Realizations { get; set; }
        public virtual DbSet<SafetyControl> SafetyControls { get; set; }
        public virtual DbSet<SafetyTraining> SafetyTrainings { get; set; }
        public virtual DbSet<SemiFinished> SemiFinisheds { get; set; }
        public virtual DbSet<SemiFinishedOrder> SemiFinishedOrders { get; set; }
        public virtual DbSet<SfOrderDetail> SfOrderDetails { get; set; }
        public virtual DbSet<SkillsForMachine> SkillsForMachines { get; set; }
        public virtual DbSet<Staff> Staffs { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<SupplierType> SupplierTypes { get; set; }
        public virtual DbSet<TechnicalProductData> TechnicalProductDatas { get; set; }
        public virtual DbSet<Technology> Technologies { get; set; }
        public virtual DbSet<Training> Trainings { get; set; }
        public virtual DbSet<Unit> Units { get; set; }
    }
}
