//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2019
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public int IdStaff { get; set; }
        public Nullable<int> IdDeparment { get; set; }
        public Nullable<int> IdPosition { get; set; }
        public Nullable<byte> Number { get; set; }
        public Nullable<System.DateTime> DateFrom { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Position Position { get; set; }
    }
}
