//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2019
{
    using System;
    using System.Collections.Generic;
    
    public partial class TechnicalProductData
    {
        public int IdProduct { get; set; }
        public byte[] Pattern { get; set; }
        public double Width { get; set; }
        public double WeightPerMeter { get; set; }
        public double Lenght { get; set; }
        public double PricePerMeter { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
