//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2019
{
    using System;
    using System.Collections.Generic;
    
    public partial class vAbsence
    {
        public int IdAbsence { get; set; }
        public string Nazwisko { get; set; }
        public string Imię { get; set; }
        public string Powód { get; set; }
        public Nullable<System.DateTime> Początek { get; set; }
        public Nullable<System.DateTime> Koniec { get; set; }
        public int IdEmployee { get; set; }
    }
}
