//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2019
{
    using System;
    using System.Collections.Generic;
    
    public partial class vDevotionsInMeasuremntsPerProcess
    {
        public int IdMeasurement { get; set; }
        public int IdProcess { get; set; }
        public int QuantityToBeProducted { get; set; }
        public Nullable<decimal> LenghtDeviation { get; set; }
        public Nullable<decimal> WidthDeviation { get; set; }
        public double LenghtAcceptableDeviation { get; set; }
        public double WidthAcceptableDeviation { get; set; }
    }
}
