//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2019
{
    using System;
    using System.Collections.Generic;
    
    public partial class vEducationForm
    {
        public int IdEducation { get; set; }
        public string Nazwisko { get; set; }
        public string Imię { get; set; }
        public string Stopień_wykształcenia { get; set; }
        public string Degree { get; set; }
        public string Tytuły_naukowe { get; set; }
        public Nullable<System.DateTime> Data_ukończenia { get; set; }
        public int IdEmployee { get; set; }
    }
}
