//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2019
{
    using System;
    using System.Collections.Generic;
    
    public partial class vEmployeeDetail
    {
        public int IdEmployee { get; set; }
        public string Nazwisko { get; set; }
        public string Imię { get; set; }
        public string Kod_pocztowy { get; set; }
        public string Miasto { get; set; }
        public string Ulica { get; set; }
        public string Nr_Domu { get; set; }
        public string Nr_lokalu { get; set; }
        public string Nr_telefonu { get; set; }
        public string PESEL { get; set; }
        public string Stopień_wykształcenia { get; set; }
        public string Tytułu_naukowe { get; set; }
        public Nullable<System.DateTime> Data_ukończenia_studiów { get; set; }
        public string Stanowisko { get; set; }
        public Nullable<System.DateTime> Początek_umowy { get; set; }
        public Nullable<System.DateTime> Koniec_umowy { get; set; }
        public Nullable<decimal> Wynagrodzenie { get; set; }
        public Nullable<System.DateTime> rening_Stanowiskowy { get; set; }
        public Nullable<System.DateTime> Data_badania_lekarskiego { get; set; }
    }
}
