//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2019
{
    using System;
    using System.Collections.Generic;
    
    public partial class vEmployeeDetails
    {
        public int IdEmployee { get; set; }
        public string EmployeeName { get; set; }
        public string EmployeeSurname { get; set; }
        public string ZipCode { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
        public string HouseNumber { get; set; }
        public string ApartmentNum { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<long> PESEL { get; set; }
        public string EducationLevel { get; set; }
        public string DegreeShort { get; set; }
        public Nullable<System.DateTime> GraduationDate { get; set; }
        public string Workplace { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public Nullable<System.DateTime> HealTestDate { get; set; }
        public Nullable<System.DateTime> WorkplaceTrainingDate { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
