//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2019
{
    using System;
    using System.Collections.Generic;
    
    public partial class vEmployeeSalesDepartment
    {
        public int Numer { get; set; }
        public string Imię { get; set; }
        public string Nazwisko { get; set; }
        public string Kod_pocztowy { get; set; }
        public string Miasto { get; set; }
        public string Ulica { get; set; }
        public string Nr_domu { get; set; }
        public string Nr_lokalu { get; set; }
        public string Telefon { get; set; }
        public string PESEL { get; set; }
        public string Dział { get; set; }
        public Nullable<System.DateTime> Data_początku { get; set; }
        public Nullable<System.DateTime> Data_końca { get; set; }
    }
}
