//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2019
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewEntranceControlHistory
    {
        public int IdSfOrder { get; set; }
        public int IdSemiFinished { get; set; }
        public int IdEmployee { get; set; }
        public decimal RealThickness { get; set; }
        public decimal RealWidth { get; set; }
        public decimal RealWeight { get; set; }
        public string RealColor { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<bool> ControlStatus { get; set; }
        public bool ChemicalComposition { get; set; }
        public string Comments { get; set; }
    }
}
