//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2019
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewSemiFinishedOrder
    {
        public int Nr_zamówienia { get; set; }
        public string Kod_półfabrykatu { get; set; }
        public string Dostawca { get; set; }
        public System.DateTime Dostarczono { get; set; }
    }
}
