//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2019
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewOshTraining
    {
        public int IdEmployee { get; set; }
        public string EmployeeName { get; set; }
        public string EmployeeSurname { get; set; }
        public string DepartmentName { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public System.DateTime TrainingDate { get; set; }
        public Nullable<byte> ValidityOfOshTraining { get; set; }
    }
}
