//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2019
{
    using System;
    using System.Collections.Generic;
    
    public partial class vInputMagazine
    {
        public int Numer { get; set; }
        public string Kod_Produktu { get; set; }
        public Nullable<int> Ilość { get; set; }
        public System.DateTime Data_przyjęcia_na_magazyn { get; set; }
    }
}
