//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2019
{
    using System;
    using System.Collections.Generic;
    
    public partial class vMaintenanceEmployeesCalendar
    {
        public int IdEmployee { get; set; }
        public int IdMaintenance { get; set; }
        public string EmployeeName { get; set; }
        public string EmployeeSurname { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string MaintenanceNr { get; set; }
    }
}
