//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2019
{
    using System;
    using System.Collections.Generic;
    
    public partial class vMaintPartsView
    {
        public string Nr_Obsługi { get; set; }
        public System.DateTime Data_przyjęcia { get; set; }
        public string Nazwa_części { get; set; }
        public int Ilość { get; set; }
        public string Jednostka { get; set; }
    }
}
