//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2019
{
    using System;
    using System.Collections.Generic;
    
    public partial class vOrder
    {
        public int Nr_zamówienia { get; set; }
        public int IdCustomer { get; set; }
        public System.DateTime Data_zamówienia { get; set; }
        public decimal Wycena { get; set; }
        public double Marża { get; set; }
        public string Pracownik { get; set; }
    }
}
