//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2019
{
    using System;
    using System.Collections.Generic;
    
    public partial class vOutsourcingWithType
    {
        public int Numer { get; set; }
        public string Typ { get; set; }
        public string Nazwa { get; set; }
        public string Telefon { get; set; }
        public string E_mail { get; set; }
        public string Miasto { get; set; }
        public string Kod_pocztowy { get; set; }
        public string Ulica { get; set; }
        public string Nr_domu { get; set; }
        public string Nr_lokalu { get; set; }
        public string NIP { get; set; }
        public string KRS { get; set; }
        public string Opis { get; set; }
    }
}
