//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2019
{
    using System;
    using System.Collections.Generic;
    
    public partial class vPartsView
    {
        public string PartName { get; set; }
        public string partType { get; set; }
        public string Producer { get; set; }
        public int CatalogPartNr { get; set; }
        public int QuantityWarehouse { get; set; }
        public string UnitName { get; set; }
    }
}
