//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2019
{
    using System;
    using System.Collections.Generic;
    
    public partial class vPartsRequestView
    {
        public int IdPartRequest { get; set; }
        public string PartName { get; set; }
        public System.DateTime RequestDate { get; set; }
        public int Quantity { get; set; }
        public int StatusPart { get; set; }
    }
}
