//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2019
{
    using System;
    using System.Collections.Generic;
    
    public partial class vPredictedPriceForCustomer
    {
        public int IdOrderCustomer { get; set; }
        public string CustomerName { get; set; }
        public System.DateTime OrderDate { get; set; }
        public decimal Cost { get; set; }
        public double Markup { get; set; }
    }
}
