//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2019
{
    using System;
    using System.Collections.Generic;
    
    public partial class vProductionProduct
    {
        public int IdProduct { get; set; }
        public string ProductCode { get; set; }
        public string SfCode { get; set; }
        public string TechnologyName { get; set; }
        public System.DateTime InputDate { get; set; }
    }
}
