//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP2019
{
    using System;
    using System.Collections.Generic;
    
    public partial class vSalariesSummary
    {
        public int IdEmployee { get; set; }
        public string EmployeeName { get; set; }
        public string EmployeeSurname { get; set; }
        public string PESEL { get; set; }
        public Nullable<decimal> DailyWage { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public int Dni_L4 { get; set; }
        public Nullable<decimal> L4Pay { get; set; }
        public int Urlop_płatny { get; set; }
        public Nullable<decimal> PAPay { get; set; }
        public int Urlop_bezpłatny { get; set; }
        public Nullable<decimal> NPAPay { get; set; }
        public int Nieusprawiedliowiona { get; set; }
        public Nullable<decimal> NPAay { get; set; }
        public int Na_żądanie { get; set; }
        public Nullable<decimal> ODPay { get; set; }
        public Nullable<double> TotalSalary { get; set; }
    }
}
